import Image from "next/image";
import Link from "next/link";
import { CalendarDays, Gem, Heart, Leaf, Sparkles, Star } from "lucide-react";
import { services } from "@/lib/services";
const highlights=[{icon:Gem,title:"Expertise",text:"Savoir-faire professionnel"},{icon:Leaf,title:"Produits premium",text:"Qualité & sécurité garanties"},{icon:Heart,title:"Sur mesure",text:"Chaque regard est unique"},{icon:Sparkles,title:"Résultat durable",text:"Tenue parfaite et confortable"}];
export default function Home(){const featured=[services[0],services[2],services[4],services[7]];return <>
<header className="site-header"><Link className="brand-lockup" href="/"><Image className="brand-logo" src="/icons/icon-512.png" alt="Erica Glow" width={58} height={58}/><span className="wordmark"><span>✦</span> Erica <em>Glow</em><small>LASH TECHNICIAN</small></span></Link><nav className="desktop-nav"><a className="active" href="#accueil">Accueil</a><a href="#apropos">À propos</a><a href="#services">Services</a><a href="#galerie">Galerie</a><a href="#avis">Avis</a><a href="#contact">Contact</a></nav><Link className="gold-button header-book" href="/reserver">Réserver <CalendarDays size={15}/></Link></header>
<section className="hero" id="accueil"><Image className="hero-image" src="/images/erica-glow-hero.png" alt="Portrait beauté mettant en valeur des cils élégants" fill priority sizes="100vw"/><div className="hero-overlay"/><div className="hero-copy"><h1>Révélez votre<br/><em>regard</em>, révélez<br/>votre <em>éclat.</em> <span>✦</span></h1><div className="flourish"><i/><b>♥</b><i/></div><p>Spécialiste en extensions de cils<br/>pour un regard naturel & sublimé.</p><div className="hero-actions"><a className="black-button" href="#services">Découvrir mes services <span>→</span></a><Link className="outline-button" href="/reserver">Prendre rendez-vous <CalendarDays size={16}/></Link></div></div></section>
<section className="highlights">{highlights.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</section>
<div className="story-services"><section className="about" id="apropos"><div className="line-art"><span>◠</span><Sparkles/></div><div><h2>À propos</h2><div className="flourish small"><i/><b>♥</b><i/></div><p>Passionnée par la beauté du regard, je mets tout mon savoir-faire au service de votre confiance.</p><p>Mon objectif : sublimer votre regard tout en respectant votre naturel.</p><a className="black-button" href="#contact">En savoir plus</a></div></section><section className="services" id="services"><div className="section-title"><div><h2>Mes services</h2><div className="flourish small"><i/><b>♥</b><i/></div></div><Link href="/services">Voir tous les tarifs <span>→</span></Link></div><div className="service-grid">{featured.map((s,i)=><article className="service-card" key={s.id}><div className={`lash-photo lash-${i+1}`}><Image src="/images/lash-styles.png" alt="" fill sizes="300px"/></div><div className="service-content"><h3>{s.name}</h3><p>{i===3?"Dépose douce et soin pour vos cils naturels.":"Résultat naturel et élégant pour un regard sublimé."}</p><strong>À partir de {s.price}€</strong></div></article>)}</div></section></div>
<section className="gallery-strip" id="galerie"><div className="gallery-intro"><Sparkles/><p>Découvrez mon travail<small>Suivez-moi sur Instagram<br/><span>@ericaglow.lashes</span></small></p></div>{[1,2,3,4,5].map(n=><div className={`gallery-shot gallery-${n}`} key={n}><Image src="/images/lash-styles.png" alt="Détail d'un regard sublimé" fill sizes="220px"/></div>)}</section>
<section className="closing"><div className="testimonial" id="avis"><div><h2>Ce que disent<br/>mes <em>clientes</em></h2><div className="flourish small"><i/><b>♥</b><i/></div></div><blockquote><b>“</b><p>Professionnelle, douce et à l’écoute.<br/>Le résultat est toujours au-delà de mes attentes !</p><span><Star size={13} fill="currentColor"/> ★★★★ · Julie D.</span></blockquote></div><div className="monogram"><Image src="/icons/icon-512.png" alt="Erica Glow" fill sizes="150px"/></div><div className="booking-cta"><h2>Prête à sublimer<br/><em>votre regard ?</em></h2><p>Prenez rendez-vous en quelques clics.</p><div className="contact-placeholder">Martigues, France<br/><span>Horaires et téléphone à confirmer</span></div><Link className="black-button" href="/reserver">Réserver maintenant <CalendarDays size={15}/></Link></div></section>
<footer id="contact"><div className="footer-brand"><div className="wordmark"><span>✦</span> Erica <em>Glow</em><small>LASH TECHNICIAN</small></div><p>Sublimer votre regard est ma passion, votre confiance ma priorité.</p></div><div><h3>Navigation</h3><a href="#accueil">Accueil</a><a href="#apropos">À propos</a><a href="#services">Services</a><a href="#galerie">Galerie</a></div><div><h3>Services</h3>{featured.map(s=><Link href={`/reserver?service=${s.id}`} key={s.id}>{s.name}</Link>)}</div><div><h3>Informations</h3><p>Martigues, France</p><p>Coordonnées à confirmer</p></div><small className="copyright">© 2026 Erica Glow — Tous droits réservés.</small></footer></>}
