"use client";

import { CheckCircle2, LockKeyhole, Star } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Booking = { id: string | number; service: string; date: string; time: string; duration?: number };
type Review = { bookingId: string; name: string; service: string; rating: number; text: string; createdAt: string };
const example = { name: "Julie D.", service: "Extension de cils", rating: 5, text: "Professionnelle, douce et à l’écoute. Le résultat est toujours au-delà de mes attentes !" };

export default function VerifiedReviews() {
  const [bookings, setBookings] = useState<Booking[]>([]), [reviews, setReviews] = useState<Review[]>([]);
  const [rating, setRating] = useState(5), [name, setName] = useState(""), [text, setText] = useState(""), [sent, setSent] = useState(false);
  useEffect(() => { setBookings(JSON.parse(localStorage.getItem("erica-glow-bookings") || "[]")); setReviews(JSON.parse(localStorage.getItem("erica-glow-reviews") || "[]")); }, []);
  const eligible = useMemo(() => bookings.find(booking => new Date(`${booking.date}T${booking.time}:00`).getTime() + (booking.duration || 60) * 60000 < Date.now() && !reviews.some(review => review.bookingId === String(booking.id))), [bookings, reviews]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!eligible || name.trim().length < 2 || text.trim().length < 10) return; const parts=name.trim().split(" "); const review: Review = { bookingId:String(eligible.id), name:`${parts[0]} ${parts[1]?.[0] || ""}.`.trim(), service:eligible.service, rating, text:text.trim(), createdAt:new Date().toISOString() }; const next=[review,...reviews]; localStorage.setItem("erica-glow-reviews",JSON.stringify(next)); setReviews(next); setSent(true); };
  return <section className="verified-reviews" id="avis"><div className="reviews-heading"><span className="eyebrow">Avis vérifiés</span><h2>Ce que disent<br/>nos <em>clientes</em></h2><p>Chaque nouvel avis est associé à un rendez-vous effectué sur cet appareil.</p></div><div className="review-cards">{[...reviews,example].slice(0,3).map((review,index)=><blockquote key={`${review.name}-${index}`}><div className="stars">{Array.from({length:5},(_,i)=><Star key={i} size={14} fill={i<review.rating?"currentColor":"none"}/>)}</div><p>“{review.text}”</p><footer><span>{review.name}</span><small><CheckCircle2/> Réservation vérifiée · {review.service}</small></footer></blockquote>)}</div><div className="review-access">{sent?<div className="review-thanks"><CheckCircle2/><h3>Merci pour votre avis !</h3><p>Votre expérience a bien été enregistrée.</p></div>:eligible?<form onSubmit={submit}><span className="eyebrow">Après votre rendez-vous</span><h3>Partagez votre expérience</h3><label>Votre note<div className="rating-buttons">{[1,2,3,4,5].map(value=><button type="button" aria-label={`${value} étoiles`} className={value<=rating?"selected":""} onClick={()=>setRating(value)} key={value}><Star fill="currentColor"/></button>)}</div></label><label>Votre prénom<input value={name} onChange={e=>setName(e.target.value)} maxLength={40}/></label><label>Votre avis<textarea value={text} onChange={e=>setText(e.target.value)} minLength={10} maxLength={400}/><small>{text.length}/400</small></label><button className="primary-button" type="submit">Publier mon avis</button></form>:<div className="review-locked"><LockKeyhole/><div><h3>Avis réservé aux clientes</h3><p>Le formulaire se débloque automatiquement après la fin d’un rendez-vous enregistré sur cet appareil.</p></div></div>}</div></section>;
}
